revad: release version v1.23.0 with all the OCM new features
cs3org/charts pull request #51
Opened 2023-03-10 09:46 UTC by SamuAlfageme

### Contributing a Chart / update to an existing Chart

- [x] Run `helm lint` on the chart dir.
- [x] (Update) Bump the `Chart.yaml` version before merging, to release it as a new version.
- [x] (Update) Replace the `annotations` on the `Chart.yaml` with:
  - `artifacthub.io/changes` - the changes introduced on the PR [with the appropiate format](https://artifacthub.io/docs/topics/annotations/helm/#supported-annotations).
  - `artifacthub.io/images` - the updated tag on the `cs3org/revad` image.
- [x] (Update) If the PR includes new configurable parameters in the chart's `values.yaml`. Add documentation in the appropiate README.

2023-03-14 13:05 UTC, SamuAlfageme commented
Setting as WIP until a new version of revad with https://github.com/cs3org/reva/pull/3723 gets released

2023-04-17 19:33 UTC, glpatcern requested changes
Prepared changes + simplified changelog for the upcoming revad version yet to be tagged.

2023-04-17 19:33 UTC, glpatcern commented on revad/Chart.yaml
> +          url: https://github.com/cs3org/reva/pull/3675
```suggestion
```

2023-04-17 19:33 UTC, glpatcern commented on revad/Chart.yaml
> +      description: Create and list OCM shares in OCS layer
```suggestion
      description: Incorporated support for OCM shares
```

2023-04-17 19:33 UTC, glpatcern commented on revad/Chart.yaml
> +          url: https://github.com/cs3org/reva/pull/3611
```suggestion
```

2023-04-17 19:33 UTC, glpatcern commented on revad/Chart.yaml
> +appVersion: v1.23.0
```suggestion
appVersion: v1.24.0
```

2023-04-17 19:33 UTC, glpatcern commented on revad/Chart.yaml
> +      image: cs3org/revad:v1.23.0
```suggestion
      image: cs3org/revad:v1.24.0
```

2023-04-17 19:33 UTC, glpatcern commented on revad/README.md
> +| `image.tag`                                | The image tag to use.                                                                                        | `v1.23.0`
```suggestion
| `image.tag`                                | The image tag to use.                                                                                        | `v1.24.0`                                                                                                                 |
```

2023-04-17 19:50 UTC, glpatcern commented on revad/Chart.yaml
> +      links:
```suggestion
```

2023-04-17 19:50 UTC, glpatcern commented on revad/Chart.yaml
>      - kind: changed
```suggestion
    - kind: added
```

2023-04-17 19:51 UTC, glpatcern commented on revad/values.yaml
> +  tag: v1.23.0
```suggestion
  tag: v1.24.0
```

2023-04-17 19:52 UTC, glpatcern approved these changes

2023-04-21 09:21 UTC, glpatcern commented
Pending on cs3org/reva#3810 to tag a new version

2023-04-21 11:57 UTC, mirekys approved these changes

2023-05-11 15:49 UTC, merged